@startuml

title __BIOSYNTHESEINHERITANCEUSE's Class Diagram__\n

  package bioSyntheseInheritanceUse {
    class AminoAcid {
        - name : String
        - formule : String
        + getName()
        + setName()
        + getFormule()
        + setFormule()
        + AminoAcid()
        + AminoAcid()
        + toString()
    }
  }
  

  package bioSyntheseInheritanceUse {
    class Base {
        - name : String
        - symbol : String
        - family : String
        ~ Base()
        - initBaseElement()
        + compl()
        + isAdenine()
        + isCytosine()
        + isGuamine()
        + isThymine()
        + isUracile()
        + getSymbol()
        + toString()
    }
  }
  

  package bioSyntheseInheritanceUse {
    class Dna {
        + Dna()
        + Dna()
        + transcriptioh()
        + getComplStrand()
    }
  }
  

  package bioSyntheseInheritanceUse {
    class Program {
        {static} ~ RED_COLOR_CODE : String
        {static} ~ RESET_CODE : String
        {static} ~ affiche()
        {static} ~ testsDisplay()
        {static} + main()
    }
  }
  

  package bioSyntheseInheritanceUse {
    class Rna {
        {static} + aminoAcidMap : HashMap<String, String>
        {static} - aminoMapExist : boolean
        {static} - getARminoMapExist()
        {static} - initAminoMap()
        + codonToAminoAcid()
        + Rna()
        + Rna()
        + Rna()
        + traduction()
    }
  }
  

  package bioSyntheseInheritanceUse {
    class Strand {
        - type : String
        - nucleoAcideList : ArrayList<Base>
        + getType()
        + setType()
        + getNucleoAcideList()
        + setNucleoAcideList()
        + Strand()
        + Strand()
        + Strand()
        + Strand()
        + Strand()
        + generateAcid()
        + toString()
    }
  }
  

  Dna -up-|> Strand
  Rna -up-|> Strand


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
